# Generated by Django 4.2.1 on 2023-09-26 16:52

from django.db import migrations, models
import django.db.models.deletion
import ranil.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hide')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ranil.models.getFileName)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranil.category')),
            ],
        ),
    ]
